### ISSUE TITLE
Background subtraction

### ISSUE THREAD

**Issue by interactivereport** [Nanostring-Biostats/CosMx-Analysis-Scratch-Space#10]
Is it needed? If so, how to perform such operation on the count matrix, either based on expression of negative probes or something else?

**Comment by patrickjdanaher** [comment]
Great question. 
Short answer, perhaps to become a short article later:
We don't backgroubd-subtract the count matrix, for two reasons:
1. there just aren't enough negprobes to get an accurate estimate of each cell's background level. If there are 20 negprobes, then a cell's total negprobe counts are binomial distributed with n = 20, p = the background rate, usually ~0.05. This is just too noisy.
2. Subtracting would turn our sparse counts matrix into a dense matrix, which uses too much memory.
