### ISSUE TITLE
Custom Stitching of Selected FOVs in the Napari-CosMx Plugin?

### ISSUE THREAD

**Issue by keiven-kun** [Nanostring-Biostats/CosMx-Analysis-Scratch-Space#106]
Hi,

Thank you for introducing the "napari-cosmx plugin" in the Nanostring Blog.

Following the steps outlined in the blog, I successfully created a napari-ready slide file from AtoMx raw data using the "stitching widget" method. However, the resulting napari file contains all the FOVs in one slide. In my CosMx experiment, I have several unrelated samples on a single slide, and I would like to view them separately in napari.

Is there a way to stitch only the selected FOVs (e.g., FOVs 10–30) together and create a napari-ready file from the raw data?

Thank you very much for your assistance!

**Comment by eveilyeverafter** [comment]
Look for the latest.fovs.csv file in the RunSummary folder and remove unwanted fovs. You may want to make a copy of the original csv.

**Comment by keiven-kun** [comment]
Thank you for your prompt response. It worked perfectly! I really appreciate it.
