### ISSUE TITLE
Stitching with Napari-cosmx plugin error

### ISSUE THREAD

**Issue by vmezzano21** [Nanostring-Biostats/CosMx-Analysis-Scratch-Space#107]
Hi Evelyn,
 I have a CosMx dataset I tried stitching using the napari-cosmx plugin but get the following error:

[NA_value_error_stitching_Napari_CosMx (1).txt](https://github.com/user-attachments/files/17263575/NA_value_error_stitching_Napari_CosMx.1.txt)

I used the napari installation set up with this yaml: 
[napari-cosmx-env_yaml.txt](https://github.com/user-attachments/files/17263597/napari-cosmx-env_yaml.txt)

Raw Data was exported from AtoMx v 1.3.2 and placed in the local machine that will stitch the files.
I wonder if there are any formatting differences that may be impeding stitching? I know that for our last dataset you were able to stitch in house but we couldn't stitch otherwise.
thanks so much for your help!!
valeria mezzano

**Comment by eveilyeverafter** [comment]
Hello Valeria. I think the info in [https://nanostring-biostats.github.io/CosMx-Analysis-Scratch-Space/posts/napari-stitching/napari-cosmx-stitching.html](https://nanostring-biostats.github.io/CosMx-Analysis-Scratch-Space/posts/napari-stitching/napari-cosmx-stitching.html) helped unblock you. Can you confirm you can stitch?

**Comment by vmezzano21** [comment]
Hi Evelyn, thanks for reaching out!Yes I have been able to stitch using using the command line option (had to replace the last two lines of the .py script to be able to print the commands).Totally different question:I realized when stitching that there is some OMERO metadata being written to the file as well. Do you know how that metadata is structured? I have tried importing to OMERO using a special zarr compatible import command but the data is not read correctly. Best!!ValeriaOn Oct 30, 2024, at 4:26 PM, Evelyn Metzger ***@***.***> wrote:﻿
Hello Valeria. I think the info in https://nanostring-biostats.github.io/CosMx-Analysis-Scratch-Space/posts/napari-stitching/napari-cosmx-stitching.html helped unblock you. Can you confirm you can stitch?

**Comment by eveilyeverafter** [comment]
There are experimental functions/routines to export ome tiffs but there is no scratch space post available yet.

**Comment by vmezzano21** [comment]
Thank you Evelyn! I’m trying to import this data to our OMEROPlus deployment using the importer ngff tool. But I get an error trying to find the ome.xml . When I ran the napari-CosMx plug-in the output had several ‘writing ome.metadata’ printed in the Terminal screen.So, I was wondering if the ome metadata needed by OMERO, is actually in there somewhere in the zarr folders or if it’s in a different format (not xml). Do you have any pointers?Thanks so much!ValeriaOn Nov 4, 2024, at 4:54 PM, Evelyn Metzger ***@***.***> wrote:﻿
There are experimental functions/routines to export ome tiffs but there is no scratch space post available yet.
