### ISSUE TITLE
Confirmation that pixel to uM factor was changed from 0.18 to 0.12?

### ISSUE THREAD

**Issue by Jwong684** [Nanostring-Biostats/CosMx-Analysis-Scratch-Space#108]
From your earliest SMI ReadMe file (https://nanostring-public-share.s3.us-west-2.amazonaws.com/SMI-Compressed/SMI-ReadMe.html), the conversion factor for pixel to uM was 0.18. This was used as a guideline for tools like CellChat, which recommended 0.18.

The Pancreas data set SMI ReadMe file (https://smi-public.objects.liquidweb.services/cosmx-wtx/Pancreas-CosMx-ReadMe.html) mentioned that the conversion rate is 0.12. On our current set up, we also see 0.12 under the Run experimental config.

Was there a change between the earliest versions of CosMx vs the commercial products?

**Comment by patrickjdanaher** [comment]
Our prototype instruments did have distinctive pixel sizes. The pixel sizes used across the history of CosMx are:

Dash: 0.180um
Alpha: 0.169um
Beta: 0.121um
Commercial CosMx: 0.121um
