### ISSUE TITLE
The process stops during stitching with napari-CosMx without any error message

### ISSUE THREAD

**Issue by mikijoyce** [Nanostring-Biostats/CosMx-Analysis-Scratch-Space#134]
Dear Support Team

Hello, I'm using napari-CosMx for stitching the CosMx data.
I can successfully load CosMx data for stitching, but the process stops during writing without any error message.
I guessed that the data is too heavy to keep the process.
Please let me know how to deal with this problem. Thank you.
<img width="736" alt="Screenshot 2024-11-26 at 17 41 19" src="https://github.com/user-attachments/assets/0f933c4c-53f2-43ae-bdd1-4cd8ac8ac451">
This is screenshot of the terminal when the process stopped.
<img width="1000" alt="Screenshot 2024-11-26 at 17 45 13" src="https://github.com/user-attachments/assets/e6df5a18-3e69-41f0-9ace-a35b5fe0d3eb">
This is the folders successfully made. In images folder, there are 6 folders (CD3, CD45, DNA, Membrane, PanCK and labels).

The size of the original data I used for stitching is 269.6GB. 

Please let me know any details, thank you.

**Comment by eveilyeverafter** [comment]
Did the program finish making the targets.hdf5 file or was there an error? 

What happens when you load the folder into napari?

**Comment by mikijoyce** [comment]
The program seems not to be finished making the targets.hdf5 file because the terminal always stops during writing the data (as I showed above as a screenshot of the terminal). When I tried to put the images data and targets.hdf5 into napari, it says there are no data in hdf5 files. 
Is it because the size of the original files are too big?

**Comment by eveilyeverafter** [comment]
I'm not sure if it's a hardware issue or something else. If you miv the hdf5 file out of that folder and try to launch napari do you see anything? Napari-CosMx should still launch without the targets.hdf5 file (it'll just not be able to plot transcripts). 

Can you confirm that you're stitching RNA data (not protein)?

**Comment by mikijoyce** [comment]
I tried and seem to succeed to launch napari-cosmx only with images folder and confirm that I'm stitching the samples like this. Is this what you meant in the previous meil? [image](https://github.com/user-attachments/assets/7d5f1579-6f5e-4eed-869d-276e11d2a6af)

**Comment by eveilyeverafter** [comment]
Thanks for confirming. I suggest taking a look at the system monitor or activity monitor while executing `read-targets` to see if you are running out RAM when creating the targets.hdf5 file.

**Comment by mikijoyce** [comment]
I have been searching the way for looking at the system monitor while executing read-targets but haven't succeeded yet.
By the way, I would like to ask you what kinds of files napari_cosmx needs for stitching? I just took out AnalysisResults, CellStatsDir, RunSummary and Spotfiles files from AtoMx then put them into napari_cosmx. Which one does napari_cosmix need to use? All of them?

**Comment by mikijoyce** [comment]
![image](https://github.com/user-attachments/assets/d1288f46-d455-4878-a77a-19fc152c958d)

I tried to make the images and hdf5 files with one-tenth datas of mine but the same thing happened anyways... I attached the screenshot of my terminal. The procedure completely stopped with this screen and the writing of hdf5 file never be finished. Do you have any solutions about this situation. Thank you very much.

**Comment by mikijoyce** [comment]
This problem has been resolved. I succeeded in making stitching file with using python command instead of making on Napari. The reason for this probably seems to be due to a lack of memory caused by opening the Napari viewer and working with it.
Thank you very much for your kindness and sorry for this inconvenience.
