### ISSUE TITLE
InSituDiff "No Commit Found"

### ISSUE THREAD

**Issue by cbumby17** [Nanostring-Biostats/CosMx-Analysis-Scratch-Space#135]
Hello,

When I try to install InSituDiff, I receive the following error:

Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref Main/_code/InSituDiff

Looking forward to trying it out!

**Comment by eveilyeverafter** [comment]
Could you give us the R code you used so we can replicate the error?

**Comment by cbumby17** [comment]
Absolutely! I copied directly from the README.md file:

devtools::install_github("https://github.com/Nanostring-Biostats/CosMx-Analysis-Scratch-Space/tree/Main/_code/InSituDiff")

I actually just tried running it again, and I no longer get the error. I will close this issue.
