### ISSUE TITLE
visualize the neighborhood of query cells in gallery view

### ISSUE THREAD

**Issue by lidanwu** [Nanostring-Biostats/CosMx-Analysis-Scratch-Space#2]
For CosMx data, select cells from metadata and then visualize the neighborhood of query cells in terms of protein staining, cell segmentation border, numeric and categorical metadata. 
![image](https://github.com/Nanostring-Biostats/CosMx-Analysis-Scratch-Space/assets/62775692/c3011b26-2bab-4005-bb75-da868199be8c)
![image](https://github.com/Nanostring-Biostats/CosMx-Analysis-Scratch-Space/assets/62775692/4f43e0be-88f0-4a3b-9036-92e31b61d5aa)

Input file structure:

- For CellStatsDir under raw data folder:

![image](https://github.com/Nanostring-Biostats/CosMx-Analysis-Scratch-Space/assets/62775692/93abb89c-9183-42c4-867d-3bef776dd5da)
![image](https://github.com/Nanostring-Biostats/CosMx-Analysis-Scratch-Space/assets/62775692/c3959a43-3cf3-465b-9973-49ea90f2ba1b)

- For ProteinDir under raw data folder:

![image](https://github.com/Nanostring-Biostats/CosMx-Analysis-Scratch-Space/assets/62775692/4ed24148-9792-4c3b-9f3f-9243237042b4)

- For napari sttiched dataset:

![image](https://github.com/Nanostring-Biostats/CosMx-Analysis-Scratch-Space/assets/62775692/3690eb58-6b76-4cde-af0f-9afbf9d8c7e2)

![image](https://github.com/Nanostring-Biostats/CosMx-Analysis-Scratch-Space/assets/62775692/9d253fb8-92d5-4169-8598-76e7454cbaac)

- example cell metadata with unique `cell_ID` in format of `c_[slide]_[fov]_[CellId]`.

![image](https://github.com/Nanostring-Biostats/CosMx-Analysis-Scratch-Space/assets/62775692/d184cbb2-cf16-4c57-a40d-f08dbbd117fd)

**Comment by eveilyeverafter** [comment]
@lidanwu, can this issue be closed?

**Comment by lidanwu** [comment]
@eveilyeverafter sure, since those figures are already in the post.
