### ISSUE TITLE
install links not working in R

### ISSUE THREAD

**Issue by grkolar** [Nanostring-Biostats/CosMx-Analysis-Scratch-Space#22]
Unable to install from repo for both the CellPoly and NeighVizGallery with similar errors:

> devtools::install_github("https://github.com/Nanostring-Biostats/CosMx-Analysis-Scratch-Space/tree/Main/_code/cellPoly")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref Main/_code/cellPoly

  Did you spell the repo owner (`Nanostring-Biostats`) and repo name (`CosMx-Analysis-Scratch-Space`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

**Comment by lidanwu** [comment]
Please try `devtools::install_github("Nanostring-Biostats/CosMx-Analysis-Scratch-Space/_code/cellPoly@Main")`
