### ISSUE TITLE
could not find fastreseg

### ISSUE THREAD

**Issue by Amelie-TGHN** [Nanostring-Biostats/CosMx-Analysis-Scratch-Space#55]
Hi,

I am trying to install the FastReseg package described in your blog post (https://nanostring-biostats.github.io/CosMx-Analysis-Scratch-Space/posts/segmentation-error-evaluation/); however, I am afraid I cannot find the repository at https://github.com/Nanostring-Biostats/FastReseg/ 

Is there any chance you could point me to it?

Thanks!

**Comment by eveilyeverafter** [comment]
The URL looks good to me. Can you confirm? 

https://github.com/Nanostring-Biostats/FastReseg

<img width="786" alt="image" src="https://github.com/Nanostring-Biostats/CosMx-Analysis-Scratch-Space/assets/5805450/8c94ffb1-7183-4ee1-bb58-873518603f49">

**Comment by Amelie-TGHN** [comment]
Hi,

Thank you for the prompt answer. I confirm it is working today, although yesterday I was directed to a 404 page not found with the same URL:

<img width="800" alt="Screenshot 2024-06-06 at 15 03 38" src="https://github.com/Nanostring-Biostats/CosMx-Analysis-Scratch-Space/assets/16762622/ea821a88-1783-44c5-b84b-2fb79f5050b0">
