### ISSUE TITLE
Stitching panel unavailable in Napari-0.4.19

### ISSUE THREAD

**Issue by NetGebremedhin** [Nanostring-Biostats/CosMx-Analysis-Scratch-Space#70]
The stitching panel is unavailable in the latest Napari versions,  0.4.19 and 0.4.19.post1

**Comment by eveilyeverafter** [comment]
Please use napari 0.4.17.

**Comment by NetGebremedhin** [comment]
Thank you. 0.4.17 does not show it either. I do not see a wheel file in 0.4.17. The stitching functionality is part of the CosMx plugin, right?

**Comment by eveilyeverafter** [comment]
The whl file can be found in the assets folder of the repo. For more info, check out the blog post:
 https://nanostring-biostats.github.io/CosMx-Analysis-Scratch-Space/posts/using-napari-for-cosmx-data/#part-2-installing-napari-cosmx

**Comment by NetGebremedhin** [comment]
Thank you. Got it. I see it the 'Stitch Images' panel in 0.4.17.
